### ISSUE TITLE
Implement User Router

### ISSUE THREAD

**Issue by leons-sky** [Apprenticeship-Projects/backend-module-project#15]
Sub task of #2

**Comment by leons-sky** [comment]
## USER
**/user** (GET - Auth Header - token) - returns user info - excludes full list of tracks
**/user** (PUT - Auth Header - token) - returns updated info
**/user** (DELETE- Auth Header - token) - delete user and session {add warning it's permanent} - redirect to homepage

**Comment by TeddyPutus** [comment]
Updates the user PUT route, incoming values are now optional and validated, can update one or many values, can update password.
