### ISSUE TITLE
Implement CRUD endpoints

### ISSUE THREAD

**Issue by leons-sky** [Apprenticeship-Projects/backend-module-project#2]

**Comment by TeddyPutus** [comment]
- [x] Create user
- [x] Login user
- [x] Logout user
- [x] Update user -> password/username/email etc.
- [x] Delete user
- [x] Create tune
- [x] Update tune
- [x] Delete tune
- [x] Get tune
- [x] Get tune meta
- [x] Get tunes (returns metadata)
- [x] Rate tune

**Comment by anammSky** [comment]
api/v1

## SESSION
**/register** (POST - username {u}, email {u & isEmail}, password {strong password stuff}, name, surname, DoB {over 13}) - redirect to login
**/session** (POST - login | username {check exists}, password {check match}) - return session token | 30 days session length(if we have time)
**/session**  (DELETE - logout - Auth Header - token) - delete session

## USER
**/user** (GET - Auth Header - token) - returns user info - excludes full list of tracks
**/user** (PUT - Auth Header - token) - returns updated info
**/user** (DELETE- Auth Header - token) - delete user and session {add warning it's permanent} - redirect to homepage 

## TUNE
**/tune** (GET - Auth Header - token- returns all track metas unless queries for specific search are added)
**/tune/id** (GET - Auth Header - token- return all track info)
**/tune** (POST - Auth Header - token) - return the track as an entry
**/tune/id** (PUT - Auth Header - token) - return the track as an entry
**/tune/id** (DELETE - Auth Header - token) - return a message
**/tune/id/rate** (POST - Auth Header - token) - return updated rating

**Comment by anammSky** [comment]
### Updated Routes
api/v1

## Register
**/register** (POST - username {u}, email {u & isEmail}, password {strong password stuff}, name, surname, DoB {over 13}) - redirect to login

## SESSION
**/session** (POST - login | username {check exists}, password {check match}) - return session token | 30 days session length(if we have time)
**/session** (DELETE - logout - Auth Header - token) - delete session

## USER
**/user** (GET - Auth Header - token) - returns user info - excludes full list of tracks
**/user** (PUT - Auth Header - token, send body updated info - NO PASSWORD) - returns updated info
**/user/change-password** (PATCH - Auth Header - token, body password)
**/user** (DELETE- Auth Header - token) - delete user and session {add warning it's permanent} - redirect to homepage

## TUNE
**/tune** (GET - Auth Header - token- returns all track metas unless queries for specific search are added)
**/tune/id** (GET - Auth Header - token- return all track info)
**/tune** (POST - Auth Header - token - send body) - return the track as an entry
**/tune/id** (PUT - Auth Header - token- send body updated info) - return the track as an entry
**/tune/id** (DELETE - Auth Header - token) - return a message
**/tune/id/rate** (POST - Auth Header - token) - return updated rating

**Comment by anammSky** [comment]
## ADMIN - User Management

**/admin/users** (GET - Auth Header - token) - returns all users
**/admin/users/:userName** (GET - Auth Header - token) - returns one user
**/admin/users/:userName** (PUT - Auth Header - token - send body updated info) - updates user - not password
**/admin/users/:userName** (DELETE - Auth Header - token) - return message
